### ISSUE TITLE
Can't Renew Certificates

### ISSUE THREAD

**Issue by germansosa** [tnozicka/openshift-acme#11]
I have an issue when certificate renew runs, the route created for well-known challenge doesn't work if the main route allow insecure traffic or redirects insecure traffic, in that case, the well-known route is ignored and all traffic goes to the main route. I think this is an issue with openshift, but, we can do something to workaround this?

I am using openshift 1.5.0

**Comment by tnozicka** [comment]
@germansosa could you also provide your route, please? I want to check the route combinations and we should file a bug to OpenShift if that proves true. I thought this should work, or at least should have failed initially and not with the renewal.

**Comment by germansosa** [comment]
@tnozicka here is my route:

```
apiVersion: v1
kind: Route
metadata:
  annotations:
    kubernetes.io/tls-acme.hash: usswMS7taGDLj0mV91f+1PFYqQZmORB2J9feJv8c+oQ=
    kubernetes.io/tls-acme.last-update-time: 2017-04-10T15:41:18Z
    kubernetes.io/tls-acme: "true"
  creationTimestamp: null
  labels:
    butter.sh/letsencrypt-managed: "yes"
  name: geoip-prod
spec:
  host: geoip.servicios.cmd.com.ar
  tls:
    certificate: |
      -----BEGIN CERTIFICATE-----
      xxx
      -----END CERTIFICATE-----
      -----BEGIN CERTIFICATE-----
      xxx
      -----END CERTIFICATE-----
    insecureEdgeTerminationPolicy: Allow
    key: |
      -----BEGIN RSA PRIVATE KEY-----
      xxx
      -----END RSA PRIVATE KEY-----
    termination: edge
  to:
    kind: Service
    name: geoip-nodejs
    weight: 100
  wildcardPolicy: None
status:
  ingress:
  - conditions:
    - lastTransitionTime: 2017-03-27T18:52:00Z
      status: "True"
      type: Admitted
    host: geoip.servicios.cmd.com.ar
    routerName: router
    wildcardPolicy: None
```

This worked initially because it did not have tls enabled, the first certificate was created from a non secure route.
