### ISSUE TITLE
Add support for NetworkPolicy

### ISSUE THREAD

**Issue by gysel** [tnozicka/openshift-acme#151]
I'd like to use a `NetworkPolicy` to restrict access from the default namespace into my project's namespace.

I use the following policy to allow the Router to send traffic to a set of pods:

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openshift-router-nginx
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
  podSelector:
    matchLabels:
      component: nginx
  policyTypes:
  - Ingress
 ```

Unfortunately the exposer pods in the projects namespace to not contain labels I can use to set up a NetworkPolicy. The only option I have is to allow traffic to all pods from the default namespace.

```
Labels:             app=exposer-6kro17vt8umfvlbh0huarjn5a5q341g2epo70mj4m6nh1oqtlh10
```

I would suggest to add a new label `component=acme` (or similar) to allow the definition of a NetworkPolicy like the following.

```yaml
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: openshift-router-acme
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: default
  podSelector:
    matchLabels:
      component: acme
  policyTypes:
  - Ingress
 ```

@tnozicka
