### ISSUE TITLE
Run on OpenShift Online

### ISSUE THREAD

**Issue by LorbusChris** [tnozicka/openshift-acme#28]
Updated with a deployable solution. WIP.

In order to run on OpenShift Online, do the following: 

Replace acme-example with your project name (namespace):
```
oc project acme-example
oc policy add-role-to-group edit system:serviceaccounts:acme-example -n acme-example
```
Then deploy the following template, specify your project name in OPENSHIFT_ACME_SELFSERVICENAMESPACE and OPENSHIFT_ACME_WATCH_NAMESPACE (or add default values for them to the template)
```
apiVersion: v1
kind: Template
metadata:
  name: acme-controller
parameters:
- description: ACME Endpoint URL
  name: OPENSHIFT_ACME_ACMEURL
  value: https://acme-staging.api.letsencrypt.org/directory
- description: Controller loglevel
  name: OPENSHIFT_ACME_LOGLEVEL
  value: "8"
- description: Name of the service pointing to ACME controller
  name: OPENSHIFT_ACME_SELFSERVICENAME
  value: acme-controller
- description: Namespace of the service pointing to a pod with this program. Defaults to current or default namespace
  name: OPENSHIFT_ACME_SELFSERVICENAMESPACE
- description: Restrics controller to namespace. If not specified controller watches for routes accross namespaces.
  name: OPENSHIFT_ACME_WATCH_NAMESPACE
- description: Docker Image of ACME controller
  name: DOCKER_IMAGE
  value: docker.io/appuio/openshift-acme
- description: Docker Image Tag of ACME controller
  name: DOCKER_IMAGE_TAG
  value: latest
objects:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: acme-controller
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: acme-controller
    labels:
      type: acme-controller
  spec:
    lookupPolicy:
      local: false
    tags:
    - annotations:
        openshift.io/imported-from: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
      from:
        kind: DockerImage
        name: ${DOCKER_IMAGE}:${DOCKER_IMAGE_TAG}
      importPolicy:
        scheduled: true
      name: latest
      referencePolicy:
        type: Source
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: acme-controller
    name: acme-controller
  spec:
    replicas: 1
    selector:
      app: acme-controller
    strategy:
      activeDeadlineSeconds: 21600
      recreateParams:
        timeoutSeconds: 600
      resources: {}
      type: Recreate
    template:
      metadata:
        labels:
          app: acme-controller
      spec:
        containers:
        - env:
          - name: OPENSHIFT_ACME_ACMEURL
            value: ${OPENSHIFT_ACME_ACMEURL}
          - name: OPENSHIFT_ACME_LOGLEVEL
            value: ${OPENSHIFT_ACME_LOGLEVEL}
          - name: OPENSHIFT_ACME_SELFSERVICENAME
            value: ${OPENSHIFT_ACME_SELFSERVICENAME}
          - name: OPENSHIFT_ACME_SELFSERVICENAMESPACE
            value: ${OPENSHIFT_ACME_SELFSERVICENAMESPACE}
          - name: OPENSHIFT_ACME_WATCH_NAMESPACE
            value: ${OPENSHIFT_ACME_WATCH_NAMESPACE}
          image: acme-controller:latest
          imagePullPolicy: IfNotPresent
          name: acme-controller
          ports:
          - containerPort: 80
            protocol: TCP
          resources:
            limits:
              cpu: '500m'
              memory: '512Mi'
            requests:
              cpu: '500m'
              memory: '512Mi'
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
        serviceAccountName: acme-controller
    test: false
    triggers:
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - acme-controller
        from:
          kind: ImageStreamTag
          name: acme-controller:latest
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: acme-controller
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
    selector:
      app: acme-controller
```
